version: '2'
services:
  redis-master:
    image: redis:alpine
    volumes:
     - ./redis-cluster/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf
  redis-standalone:
    image: redis:alpine
  erasure:
    image: erasuretester:latest
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
  benchmark:
    image: erasuretester:latest
    command: python3 -u /opt/erasuretester/benchmark.py
    cap_add:
      - SYS_ADMIN
    devices:
      - "/dev/fuse"
    volumes:
      - ./results:/opt/erasuretester/results
